# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast # Checks for syntax errors in Python files
      - id: check-docstring-first # Ensures docstrings are at the top of modules/classes/functions
  # Removed Black in favor of Ruff's formatter for a unified toolchain.
  # Ruff's formatter (ruff-format) is generally compatible with Black's style
  # and allows for a single tool to handle both linting and formatting.
  # - repo: https://github.com/psf/black # REMOVED: Commented-out Black config
  #   rev: 23.11.0 # Use the latest stable version
  #   hooks:
  #     - id: black
  #       language_version: python3.11 # Specify your Python version, adjust if needed
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9 # Use the latest stable version (ensure this is kept up-to-date)
    hooks:
      - id: ruff
        # Automatically fix linting errors and fail if any unfixed issues remain
        args: ["--fix", "--exit-non-zero"]
        # Ensure Ruff checks for formatting issues as well
      - id: ruff-format # Enforces formatting via Ruff (like Black)
        # Fail if code is not formatted (prevents unformatted commits)
        args: ["--check"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        # Use -c for config file; pyproject.toml is the standard location
        # Ensure Bandit runs with appropriate severity and confidence levels for better security checks
        args: ["-r", ".", "-c", "pyproject.toml", "--severity-level", "HIGH", "--confidence-level", "HIGH"]
        # Ensure Bandit is configured to fail the commit if security issues are found.

# REMOVED: Commented-out section for other pre-commit hooks
# Add other pre-commit hooks as needed, for example:
# - repo: https://github.com/psf/black