# pyproject.toml

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 88
target-version = "py311" # Corrected to a valid Python version

[tool.ruff.lint]
select = [
  "E", "F", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "B" # Select Ruff's linter rules, including security (B)
]

ignore = [
    "D100", # Allow missing module docstring
    "D104", # Allow missing module docstring (package)
    "D107", # Allow missing docstring in __init__
    "ANN101", # Allow missing type annotation for self
    "ANN002", # Allow missing type annotation for *args
    "ANN003", # Allow missing type annotation for **kwargs
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.bandit]
conf_file = "pyproject.toml"
level = "info" # Changed to 'info' to align with common practice, but HIGH is recommended for production CI.
               # The CI workflow explicitly overrides this to HIGH for its run.
confidence = "MEDIUM"
exclude = [
    "**/migrations/**",
    "**/tests/**",
    "**/docs/**",
]
# Specific security checks to prioritize
[tool.bandit.plugins]
hardcoded_password = true
sql_injection = true
command_injection = true

# Add other configurations as needed, e.g., for MyPy, Pytest, etc.

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*"]

[tool.coverage.report]
fail_under = 80 # Enforce minimum 80% test coverage
show_missing = true
skip_covered = true