# pyproject.toml

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Added "COM" for trailing commas
select = ["E", "F", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "B", "BLK", # Black compatibility
"A", "C4", "DTZ", "ERA", "ISC", # Import sorting
"ICN", "PIE", "PT", "RSE", "RET", "SIM", "TID", "TCH", "INT", "ARG", "PERF", "FURB", "RUF", "COM"]
ignore = ["D100", "D104", "D107", "ANN101", # Allow missing type annotation for self
"ANN002", "ANN003"] # Ignore missing module docstrings, __init__ docstrings, self/cls type hints

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.bandit]
conf_file = "pyproject.toml"
# The self-analysis indicated an invalid 'null' value for Bandit's level.
# Replacing 'severity_level' and 'confidence_level' with a single 'level'
# setting to resolve the parsing error and enable scans.
level = "info"
# Other Bandit configurations can be added here as needed.
# For example:
# exclude_dirs = [
#         "venv",
#         ".git",
#         "__pycache__",
#         "tests"
#     ]
# skip_checks = null