# pyproject.toml

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Added "COM" for trailing commas
select = ["E", "F", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "B"] # Black compatibility

ignore = [
    "D100", # Allow missing module docstring
    "D104", # Allow missing module docstring (package)
    "D107", # Allow missing docstring in __init__
    "ANN101", # Allow missing type annotation for self
    "ANN002", # Allow missing type annotation for *args
    "ANN003", # Allow missing type annotation for **kwargs
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.bandit]
# Exclude test files from comprehensive scans, as they often contain mock vulnerabilities
exclude_dirs = [
        "venv",
        ".git",
        "__pycache__",
        "tests"
    ]
level = "info" # Set to 'info' to enable scanning for all severity levels
recursive = true
config_file = "pyproject.toml"