# pyproject.toml

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]
line-length = 88
target-version = "py311" # Explicitly set target Python version

[tool.ruff.lint]
select = [
  "E", "F", "W", "C90", "I", "N", "D", "UP", "ANN", "ASYNC", "B" # Select Ruff's linter rules, including security (B)
]

ignore = [
    "D100", # Allow missing module docstring
    "D104", # Allow missing module docstring (package)
    "D107", # Allow missing docstring in __init__
    "ANN101", # Allow missing type annotation for self
    "ANN002", # Allow missing type annotation for *args
    "ANN003", # Allow missing type annotation for **kwargs
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.bandit]
conf_file = "pyproject.toml"
# Exclude directories from Bandit scans to improve performance and reduce noise
exclude = [
  "tests/",
  "docs/",
  "venv/",
  ".venv/",
  "env/",
  ".env/",
]
# Add specific Bandit configurations for better security scanning
[tool.bandit.custom_rules]
# Example: Disallow use of pickle
# 101: ['pickle', 'used']

# Configure Bandit severity and confidence levels for CI/pre-commit hooks
# These levels are used by the CI workflow and pre-commit hooks if not overridden there.
# Setting them here provides a baseline configuration.
severity_level = "HIGH" # Scan for Low, Medium, and High severity issues
confidence_level = "HIGH" # Scan for Low, Medium, and High confidence issues
level = "info" # Add level for Bandit configuration

# Add other configurations as needed, e.g., for MyPy, Pytest, etc.

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*"]

[tool.coverage.report]
fail_under = 80 # Enforce minimum 80% test coverage
show_missing = true
skip_covered = true