# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # Cache pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install ruff and black explicitly if not in requirements.txt, or ensure they are.
        # For this example, assuming they are in requirements.txt or installed by pre-commit setup.
        # If not, add: pip install ruff black
    - name: Run Ruff (Linter & Formatter Check)
      # Ruff can act as both linter (flake8 replacement) and formatter (black replacement)
      # --output-format=github makes annotations appear directly in GitHub PRs
      run: |
        ruff check . --output-format=github
        ruff format . --check
    - name: Run Pytest
      run: |
        pytest
    # You could add more steps here, e.g., for security scanning (Bandit), deployment, etc.