# .github/workflows/ci.yml
name: CI/CD Pipeline

on: [push, pull_request] # Corrected 'on:' syntax

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4 # Updated to v4 as suggested
      with: { python-version: '3.11' } # Corrected 'with:' syntax for single item

    - name: Install dependencies and Test Tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Explicitly install Ruff, coverage, and Bandit for CI to ensure they are available and correct versions
        pip install ruff pytest pytest-cov bandit # Consolidated installation

    - name: Run Ruff (Linter Check)
      shell: bash
      run: |
        ruff check . --output-format=github --exit-non-zero-on-fix
    - name: Run Ruff (Formatter Validation)
      shell: bash
      run: |
        ruff format --check --diff --exit-non-zero-on-fix
    - name: Run Bandit Security Scan
      shell: bash
      run: |
        # Use stricter levels for CI, overriding pyproject.toml if needed, or ensuring pyproject.toml is strict
        bandit -r . --config pyproject.toml --severity-level HIGH --confidence-level MEDIUM --exit-on-error
    - name: Run Unit and Integration Tests with Coverage Check
      shell: bash
      run: |
        pytest tests/ --cov=src --cov-report=xml --junitxml=report.xml --cov-fail-under=80
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          report.xml
          coverage.xml

    # You could add more steps here, e.g., for deployment, etc.