# .github/workflows/ci.yml
name: CI Pipeline

on: [push, pull_request] # Corrected 'on:' syntax

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4 # Updated to v4 as suggested
      with: { python-version: '3.11' } # Corrected 'with:' syntax for single item

    - name: Install dependencies and Test Tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install all dependencies including dev/test tools

    - name: Run Code Quality & Security Checks
      shell: bash
      run: |
        chmod +x scripts/run_quality_checks.sh
        ./scripts/run_quality_checks.sh

    - name: Run Unit and Integration Tests with Coverage Check
      shell: bash
      id: run_tests # Added ID to reference outcome
      run: |
        # Run pytest, collect coverage data, generate XML report for upload, and fail if coverage is below 80%
        pytest tests/ --cov=src --cov-report=xml --junitxml=report.xml --cov-fail-under=80
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          report.xml
          coverage.xml
          coverage.json # Also upload coverage.json for potential further analysis

    - name: Fail build on coverage threshold violation
      if: steps.run_tests.outcome == 'failure'
      run: |
        echo "Test coverage is below the required threshold (80%). Failing the build."
        exit 1

    # You could add more steps here, e.g., for deployment, etc.